%include "TemplateMacros.i"

VALIDTYPE_TEMPLATE(float)
VALIDTYPE_TEMPLATE(double)
VALIDTYPE_TEMPLATE(char)
VALIDTYPE_TEMPLATE(short)
VALIDTYPE_TEMPLATE(int)
VALIDTYPE_TEMPLATE(long)
UNSIGNED_VALIDTYPE_TEMPLATE(char)
UNSIGNED_VALIDTYPE_TEMPLATE(short)
UNSIGNED_VALIDTYPE_TEMPLATE(int)
UNSIGNED_VALIDTYPE_TEMPLATE(long)
