%include "TemplateMacros.i"

VALIDTYPE_TEMPLATE(float)
VALIDTYPE_TEMPLATE(double)
VALIDTYPE_TEMPLATE(char)
VALIDTYPE_TEMPLATE(short)
VALIDTYPE_TEMPLATE(int)
VALIDTYPE_TEMPLATE(long)
VALIDTYPE_TEMPLATE(unsigned char)
VALIDTYPE_TEMPLATE(unsigned short)
VALIDTYPE_TEMPLATE(unsigned int)
VALIDTYPE_TEMPLATE(unsigned long)
